freeCodeCamp/PhoneIDE

- pubspec.yaml
Reverts freeCodeCamp/PhoneIDE#22
> Revert "fix(deps): update dependency webview_flutter to v3"

- pubspec.lock
- pubspec.yaml
> chore: update highlighting plugin

- ios/Podfile.lock
- lib/controller/editor_view_controller.dart
- lib/controller/file_controller.dart
- lib/editor/editor.dart
- lib/editor/file_explorer/file_explorer.dart
- lib/main.dart
- lib/models/directory_model.dart
- lib/models/editor_options.dart
- lib/models/file_dir_creation_model.dart
- lib/models/file_model.dart
- pubspec.lock
ref: [#843](https://github.com/freeCodeCamp/mobile/pull/843)
> fix: make editable region line up IOS

- CHANGELOG.md
- pubspec.yaml
> chore: release 1.0.2

- lib/editor/editor.dart
> fix: linebar logic

- CHANGELOG.md
- pubspec.yaml
> chore: release v1.0.3

- lib/editor/editor.dart
> fix: alignment bug

- CHANGELOG.md
- pubspec.yaml
> chore: releae v1.0.4

- CHANGELOG.md
- pubspec.yaml
> chore: release v1.1.0

- lib/editor/editor.dart
> fix: disable smart punctuation

- CHANGELOG.md
- pubspec.yaml
> chore: release v1.1.1

- CHANGELOG.md
> fix: format changelog correctly

- android/build.gradle
- example/pubspec.lock
- example/pubspec.yaml
- lib/controller/custom_text_controller.dart
- lib/editor/editor.dart
- lib/editor/linebar.dart
- pubspec.lock
- pubspec.yaml
> chore: migrate code to flutter 3.10

- CHANGELOG.md
- pubspec.yaml
> chore: release 1.2.1

- CHANGELOG.md
- example/pubspec.lock
- pubspec.lock
- pubspec.yaml
> chore: release v1.2.2

- example/pubspec.lock
- example/pubspec.yaml
- ios/Flutter/AppFrameworkInfo.plist
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner.xcworkspace/contents.xcworkspacedata
- ios/Runner/Info.plist
- lib/editor/editor.dart
- lib/editor/linebar.dart
- pubspec.lock
> chore: migrate code to flutter 3.16

- CHANGELOG.md
- pubspec.yaml
> chore: release v1.2.3

- example/pubspec.lock
- lib/editor/editor.dart
- pubspec.lock
fix:
- challenge seed with a single line of code will now show.
- The gutter had syntax highlighting for javascript challenges
- Now calculates gutter numbers correctly on init.
> fix: multiple small issues

- CHANGELOG.md
- pubspec.yaml
> chore: release  v1.2.4

- lib/editor/editor.dart
> fix: replace single & multiple smart quotes by regular ones

- lib/editor/editor.dart
> feat: add focused textfield stream

- CHANGELOG.md
- pubspec.yaml
> chore: update version to 1.3.0+1

- CHANGELOG.md
- example/pubspec.lock
- pubspec.lock
- pubspec.yaml
> chore: update version to 1.5.0

- lib/editor/editor.dart
Checklist:
Closes freeCodeCamp/mobile/issues/1439
Closes freeCodeCamp/mobile/issues/1438
> fix: update text handling to account for region presence and adjust scrolling behavior
